# Generated by Django 4.2.1 on 2023-06-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0002_rename_adahar_no_aadhar_aadhar_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhar',
            name='updated_date',
        ),
    ]
