# Generated by Django 4.2.1 on 2023-06-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0003_remove_aadhar_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhar',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
